library (tidyverse)
args <- commandArgs(trailingOnly=TRUE)
quant_dir <- args [1]
#quant_dir <- '../data/quant/'

#' Caculate mean and average HU intensity across two sides of the brain
#' `xx`: dataframe generated by `segmentation/seg_terr.py`
mean_diff_HU <- function (xx){
    ID <- xx$ID
    xx <- xx %>% select (!ID)
    # separate into different dataframes based on column names
    # 4 combinations: left/right volume/mean HU
    Left <- xx %>% select (starts_with ('L_'))
    Right <- xx %>% select (starts_with ('R_'))
    LHU <- Left %>% select (ends_with ('_HU'))
    Lvol <- Left %>% select (ends_with ('_vol'))
    RHU <- Right %>% select (ends_with ('_HU'))
    Rvol <- Right %>% select (ends_with ('_vol'))

    # make sure the colnames are the same across dataframes
    colnames (LHU) <- gsub ('^L_|^R_|_HU$|_vol$', '', colnames (LHU))
    colnames (Lvol) <- gsub ('^L_|^R_|_HU$|_vol$', '', colnames (Lvol))
    colnames (RHU) <- gsub ('^L_|^R_|_HU$|_vol$', '', colnames (RHU))
    colnames (Rvol) <- gsub ('^L_|^R_|_HU$|_vol$', '', colnames (Rvol))

    # make sure the colnames are in the same order
    Lvol <- Lvol [, colnames (LHU)]
    Rvol <- Rvol [, colnames (LHU)]
    RHU <- RHU [, colnames (LHU)]

    # average HU of left and right sides weighted by volumes
    diff_HU <- abs (RHU-LHU)
    avg_HU <- (RHU*Rvol+LHU*Lvol)/(Rvol+Lvol)

    colnames (diff_HU) <- paste ('diff_', colnames (diff_HU), sep='')
    colnames (avg_HU) <- paste ('avg_', colnames (avg_HU), sep='')
    comb <- cbind (diff_HU, avg_HU)
    rownames (comb) <- ID
    return (comb)
}

df1<- read.csv (paste (quant_dir, 'tissue.csv' , sep='/')) %>% select (!X)
df2<- read.csv (paste (quant_dir, 'artery2.csv', sep='/')) %>% select (!X)
df3<- read.csv (paste (quant_dir, 'artery1.csv', sep='/')) %>% select (!X)
comb_df <- do.call (cbind, list(df1, df2, df3))
comb_df <- mean_diff_HU (comb_df)
write.csv (comb_df, paste (quant_dir, 'comb.csv', sep='/'))
